name: simple-test
on: [push,workflow_dispatch]

jobs:
  hello-world:
    runs-on: arm-custom-runner-5
    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/armcompiler/bin:/opt/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi/bin:/opt/VHT
      ARMLMD_LICENSE_FILE: /opt/data.dat
      ARM_TOOL_VARIANT: ult
    steps:
      - name: Test case
        run: |
          source /etc/profile.d/avh.sh
          echo $PATH
          armclang --version
          grep HOSTID /opt/data.dat
          grep USER /opt/data.dat
