# Example CI flow, for building Total-Solution Keyword application and then execute upon AVH-Corstone virtual platform.

name: simple-test
on: [push,workflow_dispatch]

jobs:
  ci_build_and_test_ats_keyword:
  
    # Specify the type of runner this job will execute within, this will be a GitHub Custom Host runner
    runs-on: arm-custom-runner-5
    
    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/armcompiler/bin:/opt/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi/bin:/opt/VHT
      ARMLMD_LICENSE_FILE: /opt/data.dat
      ARM_TOOL_VARIANT: ult
    steps:
      # Get the source code
      - name: Test case
        run: |
          ls -la
          echo "done ls"
      
      # Boostrap the environment
      - name: Bootstrap environment
        run : |
          ./bootstrap.sh
          
      # Simple workflow just to prove we are still alive (remove from final revision)
      - name: Test case
        run: |
          source /etc/profile.d/avh.sh
          echo $PATH
          armclang --version
          echo "compiler check done"
          grep HOSTID /opt/data.dat
          grep USER /opt/data.dat
