# Example CI flow, for building Total-Solution Keyword application and then execute upon AVH-Corstone virtual platform.

name: simple-ci
on: [push,workflow_dispatch]

jobs:
  ci_build_and_test_ats_keyword:

    # Specify the type of runner this job will execute within, this will be a GitHub Custom Host runner
    runs-on: arm-custom-runner-7

    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/armcompiler/bin:/opt/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi/bin:/opt/VHT
      ARMLMD_LICENSE_FILE: /opt/data.dat
      ARM_TOOL_VARIANT: ult
      LD_LIBRARY_PATH: /opt/VHT

    steps:
      # Get the source code, the command below is an official github action command.
      - uses: actions/checkout@v2

      - name: Test case
        working-directory: ./application
        run: |
          ls -la
          echo "done ls"
          env
          #ls -lia /opt
          ls -lia /opt/VHT


      # BOOTSTRAP the environment
      - name: Bootstrap environment
        working-directory: ./application
        run : |
          ./ats.sh bootstrap

      # INSTALL tools needed by the build
      - name: Install tools
        run : |
          sudo apt install python3.8-venv
          echo "-----------------------------------"
          python3.8 -m pip install imgtool cbor2
          echo "-----------------------------------"
          python3.9 -m pip install imgtool cffi intelhex cbor2 cbor pytest click

      # BUILD the KWS application
      - name: Build application
        working-directory: ./application
        run : |
          ./ats.sh build kws --target Corstone-310

      # RUN the KWS application
      - name: Build application
        working-directory: ./application
        run : |
          ./ats.sh run kws --target Corstone-300 --timelimit 7

      # Simple workflow just to prove we are still alive (remove from final revision)
      - name: End Test case
        run: |
          cat /etc/profile.d/avh.sh
          echo $PATH
          armclang --version
          echo "compiler done"
